<?php

/**
 * @file
 * Contains disc.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function disc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the disc module.
    case 'help.page.disc':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Dependency Injection, Services, Containers') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function disc_theme() {
  return [
    'disc' => [
      'render element' => 'children',
    ],
  ];
}
